name: C compile test

on:
  push:
    branches: [ current, develop, wip ]
  pull_request:
    branches: [ current ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: tbon_test
      run: make -C test
