name: C compile test

on:
  push:
    branches: [ current, develop, wip ]
  pull_request:
    branches: [ current ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: tbon_test_compile
      run: cc -Ibuild test/tbon/tbon_test.c build/libcton.o -o tbon_test
    - name: tbon_test_run
      run: ./tbon_test test/tbon/data1.tbon
